#ifndef _BC_DEF_H_
#define _BC_DEF_H_

#define BC_SYMMETRY 11
#define BC_MASSFLOW_OUTLET_MOVING -10
#define BC_MASSFLOW_OUTLET_FIXED 10
#define BC_MASSFLOW_INLET_MOVING -9
#define BC_MASSFLOW_INLET_FIXED 9
#define BC_DIRECTSTATE_OUTLET_MOVING -8
#define BC_DIRECTSTATE_OUTLET_FIXED 8
#define BC_DIRECTSTATE_INLET_MOVING -7
#define BC_DIRECTSTATE_INLET_FIXED 7
#define BC_POROUS_WALL_MOVING -6
#define BC_POROUS_WALL_FIXED 6
#define BC_OUTLET_MOVING -5
#define BC_OUTLET_FIXED 5
#define BC_INLET_MOVING -4
#define BC_INLET_FIXED 4
#define BC_ADIABATIC_WALL_MOVING -3
#define BC_ADIABATIC_WALL_FIXED 3
#define BC_SLIP_WALL_MOVING -2
#define BC_SLIP_WALL_FIXED 2
#define BC_ISOTHERMAL_WALL_MOVING -1
#define BC_ISOTHERMAL_WALL_FIXED 1
#define BC_INTERNAL 0

#define BC_MIN_CODE -10
#define BC_MAX_CODE 11


#define BC_KIRCHHOFF_SURFACE 12


#define BC_FREE         0
#define BC_FIXED        1
#define BC_MATCHED      2
#define BC_MATCHEDSLIDE 3 
#define BC_CONSTRAINED  4 
#endif
